### ISSUE TITLE
Find a way to better organize shadows

### ISSUE THREAD

**Issue by brunogeronimo** [tourstream/fti-portal-styleguide#45]
At the moment all the components that we have on the styleguide are using a different kind of shadow, which makes difficult to maintain. E.g.: If we need to have a unique colour for all the shadows we have, it might be a difficult task since we will have to search by `box-shadow` in the project and replace them manually. We should think on a way to make it more simple.

**Comment by BirgitPohl** [comment]
We have collected shadows in the variables. 
There is for sure a review needed by the designers. This requires a longer discussion and should be a bigger common task for both designers and developers. 
Therefore, I guess this issue can be closed? @brunogeronimo

**Comment by brunogeronimo** [comment]
Yes, I think we can close this now. Maybe we can have a discussion in the future in order to have a default shadow for the entire styleguide or something like this, but the main point of this issue is solved.
